"""Real-browser media behaviour suite (T8) for the portfolio.

Runs against the NETWORKED build on 8766 (vite build served by scripts/serve.mjs
under /mingzhe-portfolio/) plus the SINGLE-FILE build on 8765.

Real test media (generated by ffmpeg) lives in dist/media/test and is injected
through the test-only window.__PORTFOLIO_TEST_MEDIA__ seam; nothing is added to
the public media registry.

Checks:
- single-file flag present only on the preview build;
- approved runtime screenshot swaps the card/hero cover; withheld media hidden;
- broken media shows the readable fallback, not a spinner;
- gallery video never autoplays; lightbox video plays over real HTTP 206 ranges
  and seeking works;
- Escape closes the lightbox first, the case dialog only on the second press;
- arrow navigation pauses the previous video; focus returns to the opener;
- locale switch / project switch / scrolling out of view all pause playback;
- zero page errors.
"""
from __future__ import annotations
import os
import sys
from pathlib import Path

PORTFOLIO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PORTFOLIO / "tests"))
from playwright.sync_api import sync_playwright  # noqa: E402
from browser_support import launch_browser, log_info  # noqa: E402

NET = os.environ.get("PORTFOLIO_NET_URL", "http://127.0.0.1:8766/mingzhe-portfolio/")
SINGLE = os.environ.get("PORTFOLIO_SINGLE_URL", "http://127.0.0.1:8767/")
PREFIX = "/mingzhe-portfolio"

FIXTURE_JS = """
window.__PORTFOLIO_TEST_MEDIA__ = [
 {id:'test-cover', projectId:'fairy', type:'screenshot',
  src:'media/test/test-poster.png', width:1280, height:720,
  alt:{en:'Test cover',zh:'测试封面'},
  caption:{en:'Test cover caption',zh:'测试封面说明'},
  evidenceKind:'runtime-recorded',
  provenance:{en:'automated media suite fixture',zh:'媒体自动化测试夹具'},
  capturedAt:'2026-09-19T00:00:00Z', versionLabel:'test-build', claimIds:[],
  publication:'approved'},
 {id:'test-video', projectId:'fairy', type:'video',
  src:'media/test/test-clip.mp4', poster:'media/test/test-poster.png',
  width:1280, height:720,
  alt:{en:'Test clip',zh:'测试视频'},
  caption:{en:'Test clip caption',zh:'测试视频说明'},
  evidenceKind:'runtime-recorded',
  provenance:{en:'ffmpeg-generated suite fixture',zh:'ffmpeg 生成的测试夹具'},
  capturedAt:'2026-09-19T00:00:00Z', versionLabel:'test-build', claimIds:[],
  publication:'approved'},
 {id:'test-broken', projectId:'fairy', type:'screenshot',
  src:'media/test/does-not-exist.png', width:640, height:360,
  alt:{en:'Broken media',zh:'失效媒体'},
  caption:{en:'Broken caption',zh:'失效说明'},
  evidenceKind:'runtime-recorded',
  provenance:{en:'broken-link fixture',zh:'失效链接夹具'},
  capturedAt:'2026-09-19T00:00:00Z', versionLabel:'test-build', claimIds:[],
  publication:'approved'},
 {id:'test-withheld', projectId:'fairy', type:'screenshot',
  src:'media/test/withheld.png', width:640, height:360,
  alt:{en:'Withheld',zh:'未批准'},
  caption:{en:'Withheld caption',zh:'未批准说明'},
  evidenceKind:'runtime-recorded',
  provenance:{en:'withheld fixture',zh:'未批准夹具'},
  capturedAt:'2026-09-19T00:00:00Z', versionLabel:'test-build', claimIds:[],
  publication:'withheld'}
];
"""

failures: list[str] = []
logs: list[str] = []


def check(name, cond, detail=""):
    logs.append(("PASS" if cond else "FAIL") + f" {name}" + (f" :: {detail}" if detail else ""))
    if not cond:
        failures.append(name)


with sync_playwright() as pw:
    browser, info = launch_browser(pw, ["--autoplay-policy=no-user-gesture-required"])
    log_info(info)

    # ---- single-file flag gate ------------------------------------------------
    page = browser.new_page(viewport={"width": 1440, "height": 900})
    page.goto(SINGLE, wait_until="networkidle", timeout=30000)
    flag_single = page.evaluate("() => !!window.__PORTFOLIO_SINGLE_FILE__")
    check("single-file build exposes flag", flag_single)
    page.close()

    page = browser.new_page(viewport={"width": 1440, "height": 900})
    errors: list[str] = []
    media_responses: list[dict] = []
    bad_urls: list[str] = []
    page.on("pageerror", lambda e: errors.append("pageerror: " + str(e)))
    page.on("console", lambda m: errors.append(m.text) if m.type == "error" else None)

    def on_response(r):
        if "media/test/" in r.url:
            media_responses.append({"status": r.status, "url": r.url,
                                    "range": r.headers.get("content-range", ""),
                                    "type": r.headers.get("content-type", "")})
        if r.status >= 400:
            bad_urls.append(f"{r.status} {r.url}")
    page.on("response", on_response)
    page.add_init_script(FIXTURE_JS)
    page.goto(NET, wait_until="networkidle", timeout=30000)
    page.wait_for_timeout(1000)
    flag_net = page.evaluate("() => !!window.__PORTFOLIO_SINGLE_FILE__")
    check("network build has no single-file flag", not flag_net)

    # cover swap on the fairy card before opening
    card = page.locator('.project-art[data-case="fairy"]').first
    check("fairy card present", card.count() == 1)
    check("card gets real-cover class", card.evaluate("el => el.classList.contains('has-real-cover')"))

    card.click()
    page.wait_for_selector('#case-dialog[open] [data-media-gallery]', timeout=10000)
    page.wait_for_timeout(800)

    hero = page.locator('[data-case-art]')
    check("hero gets real-cover class", hero.evaluate("el => el.classList.contains('has-real-cover')"))
    items = page.locator('[data-media-gallery] .media-item')
    n = items.count()
    check("gallery shows 3 approved items (cover, video, broken), withheld excluded", n == 3, f"count={n}")
    check("withheld media absent", page.locator('[data-media-open="test-withheld"]').count() == 0)

    gallery_video = page.locator('video[data-media-video]')
    check("gallery video exists", gallery_video.count() == 1)
    check("gallery video does not autoplay", gallery_video.evaluate("v => v.paused"))

    # broken media fallback
    broken = page.locator('.media-item.media-screenshot', has_text="")
    broken_state = page.evaluate(
        """() => {
          const f = document.querySelector('[data-media-open="test-broken"]');
          if(!f) return 'missing-figure';
          const img = f.querySelector('img');
          return f.dataset.mediaState === 'error' ? 'error' : (img && img.complete ? 'loaded' : 'pending');
        }""")
    check("broken media enters error state", broken_state == "error", broken_state)
    broken_note_visible = page.evaluate(
        """() => {const f=document.querySelector('[data-media-open="test-broken"]');
          const n=f&&f.querySelector('[data-media-broken]');
          return n&&getComputedStyle(n).display!=='none';}""")
    check("broken media fallback note visible", bool(broken_note_visible))

    # open lightbox on the video
    page.locator('[data-media-open="test-video"]').click()
    box = page.locator('[data-media-lightbox]')
    page.wait_for_selector('[data-media-lightbox]:not([hidden]) video[data-media-lightbox-video]', timeout=10000)
    lb_video = page.locator('video[data-media-lightbox-video]')
    check("lightbox opens for video", box.is_visible())
    page.wait_for_timeout(800)
    played = lb_video.evaluate(
        """async v => {
          try { await v.play(); } catch(e) { return 'play-rejected: '+e.name; }
          await new Promise(r=>setTimeout(r,400));
          v.currentTime = 3.0;
          await new Promise(r=>setTimeout(r,900));
          return {time: v.currentTime, paused: v.paused, ready: v.readyState};
        }""")
    check("lightbox video plays and seeks", isinstance(played, dict) and played["time"] > 2.5 and played["ready"] >= 3, str(played))

    range_hits = [m for m in media_responses if m["url"].endswith(".mp4")]
    partial = [m for m in range_hits if m["status"] == 206]
    check("mp4 served as video/mp4", any("video/mp4" in m["type"] for m in range_hits),
          str(sorted({m["type"] for m in range_hits})))
    check("real HTTP 206 range responses observed for seek", len(partial) >= 1,
          str([(m["status"], m["range"]) for m in range_hits][:4]))

    # arrow navigation moves media and pauses previous
    page.keyboard.press("ArrowRight")
    page.wait_for_timeout(700)
    stage_img = page.locator('[data-media-stage] img').count()
    check("arrow moves to next (image) item", stage_img == 1, f"stage imgs={stage_img}")
    page.keyboard.press("ArrowLeft")
    page.wait_for_timeout(700)

    # first Escape closes lightbox only
    page.keyboard.press("Escape")
    page.wait_for_timeout(500)
    check("first Escape closes lightbox", page.locator('[data-media-lightbox]').is_hidden())
    check("case dialog still open after first Escape", page.evaluate("() => document.getElementById('case-dialog').open"))

    # second Escape closes the dialog
    page.keyboard.press("Escape")
    page.wait_for_timeout(500)
    check("second Escape closes case dialog", not page.evaluate("() => document.getElementById('case-dialog').open"))

    # reopen: lightbox open -> locale switch closes lightbox and pauses
    card.click()
    page.wait_for_selector('#case-dialog[open] [data-media-gallery]', timeout=10000)
    page.wait_for_timeout(500)
    page.locator('[data-media-open="test-video"]').click()
    page.wait_for_selector('[data-media-lightbox]:not([hidden]) video', timeout=10000)
    page.wait_for_timeout(400)
    # lightbox covers the toolbar; force-click dispatches the real handler anyway
    page.locator('[data-case-locale]').click(force=True)
    page.wait_for_timeout(1200)
    check("locale switch closes lightbox", page.locator('[data-media-lightbox]').is_hidden())
    all_paused = page.evaluate("() => [...document.querySelectorAll('video')].every(v=>v.paused)")
    check("all videos paused after locale switch", all_paused)

    # offscreen pause: play gallery video then scroll the dialog far down
    gv = page.locator('video[data-media-video]')
    gv.evaluate("""async v => {try{await v.play()}catch(e){}}""")
    page.wait_for_timeout(500)
    playing_now = gv.evaluate("v => !v.paused")
    page.evaluate("""() => {const s=document.querySelector('.case-scroll');if(s)s.scrollTop=s.scrollHeight;}""")
    page.wait_for_timeout(1500)
    after_scroll = gv.evaluate("v => v.paused")
    check("gallery video could start (autoplay policy ok)", playing_now)
    check("gallery video pauses when scrolled out of view", after_scroll)

    # project switch pauses/removes media cleanly
    page.evaluate("window.scrollTo(0,0)")
    page.wait_for_timeout(300)
    page.locator('[data-case-next]').first.click()
    page.wait_for_timeout(1200)
    leftover_playing = page.evaluate("() => [...document.querySelectorAll('video')].filter(v=>!v.paused).length")
    check("no video keeps playing after project switch", leftover_playing == 0, f"playing={leftover_playing}")
    page.keyboard.press("Escape")
    page.wait_for_timeout(400)

    real_errors = [e for e in errors if "favicon" not in e.lower() and "Download the React DevTools" not in e]
    # The deliberately broken fixture produces one expected 404; anything else fails.
    unexpected_bad = [u for u in bad_urls if "does-not-exist.png" not in u and "favicon" not in u]
    # Generic "Failed to load resource" console lines map to the expected 404.
    real_errors = [e for e in real_errors if not (e.startswith("Failed to load resource") and "404" in e and not unexpected_bad)]
    check("only the deliberate broken fixture 404s", not unexpected_bad, str(unexpected_bad))
    check("zero unexpected page/console errors", not real_errors, " | ".join(real_errors[:3]))
    browser.close()

print("\n".join(logs), flush=True)
print(f"[media-responses] {len(media_responses)} media requests", flush=True)
if failures:
    print(f"[FAIL] {len(failures)} media behaviour checks failed:")
    for f in failures:
        print(" -", f)
    sys.exit(1)
print("[PASS] media behaviour suite passed over real HTTP with real media")
