import type { Locale } from './state.js';
export type ProjectCopy = { category: string; summary: string; role: string; status: string; evidence: string; limits: string; features: string[]; challenge: string };
export type Project = {id: string; name: string; short: string; kind: 'ai' | 'archive'; stack: string[]; url: string | null; en: ProjectCopy; zh: ProjectCopy};
export const profile = {
 "name": "Mingzhe Zhang",
 "alias": "Richie",
 "city": "Melbourne, Australia",
 "email": "zmz1998@gmail.com",
 "github": "https://github.com/babyzmz",
 "resume": "./documents/Mingzhe_Zhang_AI_Developer_Resume.pdf",
 "role": {
  "en": "AI Application Developer",
  "zh": "AI 应用开发者"
 }
};
export const projects: Project[] = [
 {
  "id": "fairy",
  "name": "Fairy",
  "short": "F",
  "kind": "ai",
  "stack": [
   "React",
   "TypeScript",
   "Tauri / Rust",
   "Python"
  ],
  "url": "https://github.com/babyzmz/Fairy-LLM",
  "en": {
   "category": "PERSONAL DEVICE AI ASSISTANT",
   "summary": "Building an intelligent assistant for personal devices, bringing conversations, document retrieval and controlled tool use into everyday work.",
   "role": "Self-directed, AI-assisted project development: requirements, provider integration, animated desktop interactions, debugging and focused validation.",
   "status": "In development · companion features in Beta",
   "evidence": "Current supplied CV and the public Fairy V3 repository describe the desktop shell, Core, capability adapters and documented release scope. Real screenshots and a blurred screen recording captured on 2026-09-19 show the permission settings, Skills/MCP catalogue, model configuration and browser-state pages of the running app.",
   "limits": "This portfolio does not run a native release build or present Beta as a production release; the website shows real captured evidence plus a visual interpretation, not an embedded desktop app. Conversation content was excluded or blurred before capture, and no private keys or local data are published.",
   "features": [
    "Local-first Windows desktop workspace with ordinary and project conversations.",
    "Model/provider integration, MCP tools and reusable Skills.",
    "Document-grounded Q&A, speech input/output and generated-file previews.",
    "Animated pet appearance, window layout and hit-testing iteration."
   ],
   "challenge": "A passing build is not the same as a usable desktop app. My work includes reproducing window and interaction issues and checking real behaviour beyond automated tests."
  },
  "zh": {
   "category": "个人终端智能助手",
   "summary": "以成为个人终端的智能助手为目标，将对话、资料检索与受控工具操作融入日常工作。",
   "role": "自主、AI 辅助的项目开发：需求拆解、模型接入、桌宠动画和窗口交互、问题排查与针对性验证。",
   "status": "持续开发 · 实时陪伴处于 Beta",
   "evidence": "依据已提供的新简历和 Fairy V3 公开仓库；仓库描述了桌面壳、Core、能力适配和发布范围。2026-09-19 实拍的截图与打码录屏展示了运行中应用的权限设置、Skills/MCP 目录、模型配置与浏览器状态页面。",
   "limits": "本次作品集未运行原生发布构建，也不把 Beta 当作正式生产版本；网站展示真实实拍证据与视觉演绎，而不是在网页里运行桌面程序。采集前已排除或模糊对话内容，不发布任何私钥或本地数据。",
   "features": [
    "本地优先的 Windows 工作空间，区分普通聊天与项目会话。",
    "模型供应商接入、MCP 工具与可复用 Skills。",
    "基于文档的问答、语音输入输出与生成文件预览。",
    "持续调整桌宠动画、窗口布局与命中区域。"
   ],
   "challenge": "构建通过并不等于桌面应用好用。开发中需要复现真实窗口与交互问题，并在自动化测试之外检查实际行为。"
  }
 },
 {
  "id": "core",
  "name": "MojoCore",
  "short": "MC",
  "kind": "ai",
  "stack": [
   "Node.js / TypeScript",
   "REST / SSE",
   "PostgreSQL",
   "Multi-language SDKs"
  ],
  "url": null,
  "en": {
   "category": "SHARED AGENT RUNTIME",
   "summary": "The shared backend foundation for MojoClaw and MojoAX, with work on recorded tasks, cancellation, retries and restoration.",
   "role": "AI-assisted backend development and iteration on shared runtime capabilities, task lifecycle, recovery and contract checks.",
   "status": "Ongoing development · private project",
   "evidence": "Source reviewed on 2026-09-21: the run gateway, SSE replay routes and conversation projection implement persistence, idempotency checks and terminal-state handling. Contribution scope follows the supplied CV. Live model and recovery acceptance were not rerun.",
   "limits": "No public runtime demo or private source is exposed here. This portfolio does not certify end-to-end production readiness. Fairy has its own Core and is not shown as a MojoCore client.",
   "features": [
    "PostgreSQL-backed runs, ordered events and cursor-based SSE replay.",
    "Idempotency keys checked against request content and identity.",
    "Consistent success, failure, cancellation and timeout handling.",
    "Shared contracts, product adapters and multi-language SDKs."
   ],
   "challenge": "A task must remain understandable after a refresh, cancellation or retry. I focus on where execution state lives and how the UI recovers it without inventing a new state."
  },
  "zh": {
   "category": "共享智能体运行核心",
   "summary": "MojoClaw 与 MojoAX 共用的后端基础，开发重点包括任务记录、取消、重复请求与刷新后的状态恢复。",
   "role": "借助 AI 开发与迭代共享后端能力、任务生命周期、恢复机制和接口契约检查。",
   "status": "持续开发 · 私有项目",
   "evidence": "2026-09-21 核对本机源码：任务网关、SSE 重放路由和会话投影包含持久化、幂等校验与终态处理。开发贡献范围依据所附简历；本次未运行真实模型或恢复验收。",
   "limits": "本站不开放私有源码或公开运行演示，也不证明整套系统已经达到生产就绪。Fairy 拥有自己的 Core，不作为 MojoCore 客户端展示。",
   "features": [
    "PostgreSQL 持久化任务、顺序事件与 SSE 游标重放。",
    "幂等键、请求内容与身份冲突校验。",
    "成功、失败、取消、超时的统一终态处理。",
    "共享契约、产品适配层与多语言 SDK。"
   ],
   "challenge": "刷新、取消、重试之后，任务仍应有明确状态。我的重点是执行状态的归属，以及界面如何恢复它，而不是自行猜测出另一套状态。"
  }
 },
 {
  "id": "claw",
  "name": "MojoClaw",
  "short": "M/",
  "kind": "ai",
  "stack": [
   "React / TypeScript",
   "Electron",
   "Core APIs",
   "SSE"
  ],
  "url": null,
  "en": {
   "category": "PERSONAL AI SAAS",
   "summary": "An AI SaaS service for individuals, bringing conversations, project tasks and generated files together across web and desktop workspaces.",
   "role": "AI-assisted application development: project/task interfaces, Core API integration, failure investigation and chat-flow smoke checks.",
   "status": "Ongoing development · private project",
   "evidence": "Source reviewed on 2026-09-21: Web/Electron structure, shared durable-run state, message ordering and HTML artifact previews. Contribution scope follows the CV; native and live chat acceptance were not rerun.",
   "limits": "The scene is an interface architecture illustration, not a live product session or screenshot. No currently verified public deployment is linked.",
   "features": [
    "Conversations, projects and tasks in React / Electron workspaces.",
    "Generated-file and HTML artifact previews.",
    "Shared durable-run state and message ordering across Web and desktop.",
    "Core-backed streaming, cancellation and conversation recovery."
   ],
   "challenge": "The frontend should show the actual state of a task. Keeping the product interface and execution core separate makes that responsibility clearer."
  },
  "zh": {
   "category": "面向个人的 AI SaaS 服务",
   "summary": "面向个人用户的 AI SaaS 服务，通过网页与桌面工作台组织对话、项目任务和生成文件。",
   "role": "使用 AI 辅助开发项目与任务界面、接入 Core API、排查失败原因并执行聊天流程冒烟检查。",
   "status": "持续开发 · 私有项目",
   "evidence": "2026-09-21 核对本机源码：Web 与 Electron 结构、共享持久化任务状态、消息排序和 HTML 生成物预览。开发贡献依据简历；本次未复测原生端或真实聊天全链路。",
   "limits": "本页是界面架构示意，不是真实产品会话或截图。未链接当前已验证的公网部署。",
   "features": [
    "React / Electron 工作台中的会话、项目与任务。",
    "生成文件与 HTML 页面预览。",
    "Web 与桌面共享任务状态和消息排序逻辑。",
    "通过 Core 接入流式任务、取消与会话恢复。"
   ],
   "challenge": "前端应该展示任务的真实状态。把产品界面与执行核心分开，可以让这个责任更清晰。"
  }
 },
 {
  "id": "ax",
  "name": "MojoAX",
  "short": "AX",
  "kind": "ai",
  "stack": [
   "React / TypeScript",
   "Tailwind CSS",
   "Electron",
   "Core APIs"
  ],
  "url": null,
  "en": {
   "category": "ENTERPRISE AI WORKBENCH",
   "summary": "An enterprise AI workbench organising reference material, files and task-relevant views around shared runtime capabilities.",
   "role": "AI-assisted enterprise UI development, shared runtime integration and translation of business-system requirements into implementation tasks.",
   "status": "Ongoing development · private project",
   "evidence": "Source reviewed on 2026-09-21: the Surface controller supports automatic selection, pinning and split view; SSO and tenant controllers call Core and are no longer described collectively as placeholders. External identity and enterprise workflows were not rerun.",
   "limits": "Not presented as a complete ERP or a fully deployed enterprise platform. Scaffolds, unverified integrations and roadmap items are not promoted to delivered features.",
   "features": [
    "Tool-driven surfaces with pinning and split view.",
    "Workspaces, projects, task activity and artifact organisation.",
    "Core integration for SSO sessions, tenant lists and switching.",
    "Distinct enterprise interaction with explicit loading and error states."
   ],
   "challenge": "The enterprise product needs its own workflow and information hierarchy, rather than just renaming the personal application."
  },
  "zh": {
   "category": "企业 AI 工作台",
   "summary": "企业 AI 工作台，围绕业务任务组织资料、文件与执行界面，通过产品适配层接入共享能力。",
   "role": "AI 辅助企业界面开发、共享运行服务接入，以及把业务系统需求转化为开发任务。",
   "status": "持续开发 · 私有项目",
   "evidence": "2026-09-21 核对本机源码：Surface 控制器支持自动召唤、固定与分屏；SSO 和租户控制器已有 Core 调用，不再笼统归为占位。外部身份服务和企业流程未在本次复测。",
   "limits": "不作为完整 ERP 或全面上线的企业平台宣传。占位结构、未验证接入与规划项不写成已交付功能。",
   "features": [
    "工具活动驱动工作面板，支持固定与分屏。",
    "工作区、项目、任务过程与生成物的信息组织。",
    "SSO 会话与租户列表、切换的 Core 接入。",
    "独立的企业交互与明确的加载、失败状态。"
   ],
   "challenge": "企业产品需要自己的工作流和信息层级，而不是简单地给个人版更换名称。"
  }
 },
 {
  "id": "dreambound",
  "name": "Dreambound Realm",
  "short": "DR",
  "kind": "archive",
  "stack": [
   "Canvas",
   "JavaScript",
   "Browser game"
  ],
  "url": "https://github.com/babyzmz/mingzhe-portfolio/tree/main/demos/dreambound",
  "en": {
   "category": "BROWSER GAME",
   "summary": "A dream-themed Canvas/WebGL2 action roguelite. The recovered build runs in the browser: chapter title, combat, blessings and run-end loop verified end to end.",
   "role": "Earlier portfolio project; the playable build is the original Canvas/WebGL2 edition, recovered from the local working copy and hosted as a static demo on this site.",
   "status": "Earlier project · playable demo hosted and verified on 2026-09-19",
   "evidence": "The game boots in a real browser with WebGL (ANGLE/D3D11): Chapter I Memory Tide title, HUD with room/build/HP, real-time combat with enemies and projectiles, blessing choices and the run-end/restart screen were exercised through a full play loop with zero console or HTTP errors.",
   "limits": "The older public GitHub copy is missing js/core/game.js (its request returned 404), so the demo on this site was recovered from the local original. The separate Unity 6 remake is not built or verified here. Character art rights should be confirmed before wider redistribution.",
   "features": [
    "Playable Canvas/WebGL2 build hosted on this site, no server required.",
    "Health, skill cooldown, rooms and enemies verified in a real run.",
    "Blessing choices, run-end screen and restart loop exercised end to end."
   ],
   "challenge": "Host only the build that was actually run to completion, and keep the older incomplete public copy labelled as the original record."
  },
  "zh": {
   "category": "浏览器游戏",
   "summary": "梦境主题的 Canvas/WebGL2 动作肉鸽游戏。恢复后的构建可在浏览器直接运行：章节标题、战斗、祝福与结算循环已端到端验证。",
   "role": "旧作品集项目；可玩版本为 Canvas/WebGL2 原版，从本地工作副本找回，作为静态演示托管在本站。",
   "status": "历史项目 · 可玩演示已托管并于 2026-09-19 验证",
   "evidence": "游戏在真实浏览器以 WebGL（ANGLE/D3D11）启动：第一章「记忆潮汐」标题、房间/构筑/生命值 HUD、带敌人与弹幕的实时战斗、祝福选择与结算重开，已完整跑通，无控制台或 HTTP 错误。",
   "limits": "较早的公开 GitHub 副本缺少 js/core/game.js（请求返回 404），本站演示由本地原版恢复；独立的 Unity 6 重制版未在本次构建或验证；角色美术的对外授权需另行确认。",
   "features": [
    "可玩 Canvas/WebGL2 构建托管在本站，无需服务器。",
    "真实运行中验证了生命、技能冷却、房间与敌人。",
    "祝福选择、结算画面与重新开始循环已端到端跑通。"
   ],
   "challenge": "只托管真正完整跑通过的构建，并把较早的不完整公开副本继续标注为原始记录。"
  }
 },
 {
  "id": "webchange",
  "name": "Web Change",
  "short": "Δ",
  "kind": "archive",
  "stack": [
   "Electron",
   "Desktop UI"
  ],
  "url": "https://github.com/babyzmz/mingzhe-portfolio/blob/main/script.js",
  "en": {
   "category": "MONITORING INTERFACE",
   "summary": "A website-change monitoring system with a Python semantic-diff engine and an Electron desktop UI. The CLI pipeline and desktop renderer were run and captured locally.",
   "role": "Earlier full-stack project: monitor configuration, semantic change detection, alert records and the desktop control-panel interface.",
   "status": "Archived project · CLI and UI renderer verified locally on 2026-09-19",
   "evidence": "The Python monitor passed its test suite (8/8), fetched a real external page, and a two-pass run against a local fixture detected a price drop (¥329 to ¥299, confidence 0.93) and wrote the alert record. The desktop UI renderer (dashboard, monitors, alerts, history, settings and add-monitor dialog) was built and captured in a real browser.",
   "limits": "Gallery stills show the renderer process only, not the packaged Electron shell: that build starts multi-GB local-model downloads on launch with no opt-out, so it was not started. Two upstream packaging issues were recorded (absolute base path breaks the file:// build; unconditional AI runtime initialisation) and left unchanged. No hosted service is linked.",
   "features": [
    "Semantic content diff with confidence scoring and alert log.",
    "Desktop control panel for monitors, alerts, history and settings.",
    "CLI pipeline verified end to end with local fixtures."
   ],
   "challenge": "Keep UI evidence labelled as renderer-only and prove monitoring behaviour through CLI runs instead of implying a packaged, hosted product."
  },
  "zh": {
   "category": "网页变化监测界面",
   "summary": "带 Python 语义差异引擎与 Electron 桌面界面的网页变化监测系统；命令行流水线与桌面渲染层已在本机运行并截图。",
   "role": "早期全栈项目：监控配置、语义变化检测、告警记录与桌面控制台界面。",
   "status": "历史项目 · CLI 与 UI 渲染层已于 2026-09-19 在本机验证",
   "evidence": "Python 监测器测试 8/8 通过，成功抓取真实外部页面；对本地夹具的两轮运行检出降价（¥329→¥299，置信度 0.93）并写入告警记录。桌面 UI 渲染层（仪表盘、监控、告警、历史、设置与新增监控对话框）已在真实浏览器中构建并截图。",
   "limits": "画廊截图仅覆盖渲染进程，不含打包后的 Electron 整壳：该构建开机即无开关下载数 GB 本地模型，因此未启动。两处上游打包问题已记录（绝对 base 路径导致 file:// 白屏、AI 运行时无条件初始化），未做修改。本站不链接托管服务。",
   "features": [
    "带置信度评分与告警日志的语义内容差异检测。",
    "管理监控、告警、历史与设置的桌面控制台。",
    "命令行流水线已用本地夹具端到端验证。"
   ],
   "challenge": "UI 证据明确标注为渲染层，监测能力用命令行实测证明，而不是暗示已有打包并托管的产品。"
  }
 },
 {
  "id": "goodnight",
  "name": "Goodnight Store",
  "short": "gn.",
  "kind": "archive",
  "stack": [
   "Next.js",
   "Commerce"
  ],
  "url": "https://github.com/babyzmz/mingzhe-portfolio/blob/main/script.js",
  "en": {
   "category": "COMMERCE EXPERIMENT",
   "summary": "A Next.js anime-goods storefront. The UI-only build (browsing, product grid, long page) was run and captured locally; the full backend edition exists separately and was not started.",
   "role": "Earlier commerce project: storefront layout, product presentation and responsive page structure.",
   "status": "Archived project · UI-only build verified locally on 2026-09-19; backend edition not run",
   "evidence": "The UI-only Next.js build served a 3,287 px storefront in a real browser with the hero, featured products and product grid, zero console errors and zero failed requests. Product imagery carries supplier SAMPLE watermarks.",
   "limits": "This edition has no backend, account, payment or order pipeline, and it is not linked as a live shop. The separate full build (Prisma, auth, uploads) contains real configuration and a database dump, so it was inventoried but neither read nor run. Product art depicts licensed-style fan goods and is shown as watermarked samples.",
   "features": [
    "Storefront hero, featured products and full product grid in Next.js.",
    "Responsive long-page layout verified in a real browser.",
    "Checkout and order management remain out of scope for this UI build."
   ],
   "challenge": "Present the storefront craft honestly: a browsable UI prototype is not an operating commerce business."
  },
  "zh": {
   "category": "电商体验探索",
   "summary": "Next.js 二次元商品店铺。纯 UI 版本（浏览、商品网格、长页面）已在本机运行并截图；完整后端版本单独存在，本次未启动。",
   "role": "早期电商项目：店铺布局、商品呈现与响应式页面结构。",
   "status": "历史项目 · UI 版本已于 2026-09-19 在本机验证；后端版本未运行",
   "evidence": "纯 UI 的 Next.js 版本在真实浏览器中呈现 3287px 店铺长页，含首页横幅、热门商品与商品网格，控制台零错误、请求零失败；商品图带有供应商 SAMPLE 水印。",
   "limits": "该版本没有后端、账号、支付或订单链路，不作为在线商店链接。独立的完整版本（Prisma、鉴权、上传）含真实配置与数据库转储，仅做目录盘点，未读取也未运行。商品图为带水印的授权风格同人样图。",
   "features": [
    "Next.js 店铺横幅、热门商品与完整商品网格。",
    "响应式长页面布局已在真实浏览器验证。",
    "结账与订单管理不在此 UI 版本范围内。"
   ],
   "challenge": "如实呈现店铺界面成果：可浏览的 UI 原型不等于实际运营的电商业务。"
  }
 },
 {
  "id": "tarot",
  "name": "AI Tarot Reports",
  "short": "✧",
  "kind": "archive",
  "stack": [
   "Next.js",
   "Generative reports"
  ],
  "url": "https://github.com/babyzmz/mingzhe-portfolio/blob/main/script.js",
  "en": {
   "category": "GENERATIVE EXPERIENCE",
   "summary": "A tarot-themed AI report generator in Next.js. The full local flow — form, shuffle, three-card draw and structured A–F report — was verified with the documented mock switch.",
   "role": "Earlier project: session form, card-draw interaction, report API and structured report layout.",
   "status": "Archived project · local mock flow verified on 2026-09-19; hosted service not deployed",
   "evidence": "Running locally without keys or a database (in-memory store, mock polishing switch), the report API returned 201 and the browser flow produced the complete report page; the UI explicitly labels mock output and repeats entertainment and non-professional-advice disclaimers.",
   "limits": "No paid model was called and no persistent hosted service is linked: durable reports need PostgreSQL and a configured provider. Two upstream findings were recorded (missing favicon, a duplicate React key for repeated cards) and left unchanged. The product is entertainment, not predictive or professional advice.",
   "features": [
    "Session form with question type, spread and draw method.",
    "Animated shuffle/draw with bilingual card names and meanings.",
    "Structured A–F report API verified in a local mock environment."
   ],
   "challenge": "Show the complete experience while labelling mock output, so a local demo never masquerades as a hosted AI service."
  },
  "zh": {
   "category": "生成式体验",
   "summary": "Next.js 塔罗主题 AI 报告生成器。表单、洗牌、三张抽牌到结构化 A–F 报告的完整本地流程，已用明示的 mock 开关验证。",
   "role": "早期项目：会话表单、抽牌交互、报告接口与结构化报告版式。",
   "status": "历史项目 · 本地 mock 流程已于 2026-09-19 验证；未部署托管服务",
   "evidence": "在无密钥、无数据库（内存存储、mock 润色开关）的本地运行中，报告接口返回 201，浏览器流程产出完整报告页；界面明确标注 mock 输出，并重申娱乐与非专业建议免责声明。",
   "limits": "未调用付费模型，也不链接持久托管服务：报告持久化需要 PostgreSQL 与已配置的供应商。已记录两处上游问题（favicon 缺失、重复牌产生重复 React key），未做修改。产品定位为娱乐，不构成预测或专业建议。",
   "features": [
    "含问题类型、牌阵与抽牌方式的会话表单。",
    "洗牌/抽牌动画与中英牌名、牌义。",
    "结构化 A–F 报告接口已在本地 mock 环境验证。"
   ],
   "challenge": "展示完整体验的同时标注 mock 输出，不让本地演示冒充托管 AI 服务。"
  }
 },
 {
  "id": "converter",
  "name": "Mi Format Converter",
  "short": "↔",
  "kind": "archive",
  "stack": [
   "Python",
   "PyQt",
   "Desktop utility"
  ],
  "url": "https://github.com/babyzmz/mingzhe-portfolio/blob/main/script.js",
  "en": {
   "category": "DESKTOP UTILITY",
   "summary": "A native Python / PyQt media converter. The released Windows executable (2024-11-25) was launched and its four modules captured in an empty workspace.",
   "role": "Earlier desktop project: image, video, m4s/concatenation and PDF conversion modules with a tabbed PyQt interface.",
   "status": "Archived project · released exe launched and UI verified on 2026-09-19; conversion jobs not re-run",
   "evidence": "The 84.9 MB Mi Format Converter.exe started on Windows with no install: image, video, m4s and PDF tabs render their parameter and output controls. The build bundles an FFmpeg.exe binary from the gyan.dev GPL essentials build.",
   "limits": "Gallery stills use an empty workspace and no conversion job was executed or timed in this round, so format coverage and accuracy are not re-certified. The original public release page is offline, so no download link is offered; a re-release would require confirming the GPL distribution notice for bundled FFmpeg.",
   "features": [
    "Tabbed native PyQt interface for image, video, m4s and PDF conversion.",
    "Bundled FFmpeg engine (gyan.dev GPL essentials build).",
    "Released executable runs without installation on Windows."
   ],
   "challenge": "Show the real shipped utility while distinguishing a launched UI from a re-tested conversion matrix, and respect FFmpeg's GPL obligations before any re-release."
  },
  "zh": {
   "category": "桌面实用工具",
   "summary": "原生 Python / PyQt 媒体格式转换器。2024-11-25 的 Windows 发布版已启动，四个模块均在空工作区实拍。",
   "role": "早期桌面项目：图片、视频、m4s/合并与 PDF 转换模块，以及分页签的 PyQt 界面。",
   "status": "历史项目 · 发布版 exe 已于 2026-09-19 启动并验证界面；本轮未重跑转换任务",
   "evidence": "84.9 MB 的 Mi格式转换.exe 免安装在 Windows 启动：图片、视频、m4s、PDF 四个页签的参数与输出控件均正常渲染；构建内置来自 gyan.dev GPL essentials 的 FFmpeg.exe。",
   "limits": "画廊截图为空工作区实拍，本轮未执行或计时任何转换任务，因此不重新背书格式覆盖与准确率。原公开发布页已下线，故不提供下载链接；若重新发布，需先确认内置 FFmpeg 的 GPL 分发声明。",
   "features": [
    "图片、视频、m4s 与 PDF 转换的原生 PyQt 分页签界面。",
    "内置 FFmpeg 引擎（gyan.dev GPL essentials 构建）。",
    "发布版 exe 可在 Windows 免安装运行。"
   ],
   "challenge": "展示真实已发布工具，同时区分“界面已启动”与“转换矩阵已复测”，并在重新发布前履行 FFmpeg 的 GPL 义务。"
  }
 }
];
export const text: Record<Locale,Record<string,string>> = {
 "en": {
  "navWork": "Work",
  "navMethod": "Process",
  "navAbout": "About",
  "navContact": "Get in touch",
  "skip": "Skip to projects",
  "role": "AI APPLICATION DEVELOPER",
  "location": "MELBOURNE, AUSTRALIA",
  "heroKicker": "INDEPENDENT BUILDER · AI & SOFTWARE",
  "heroA": "Ideas into",
  "heroB": "intelligence.",
  "heroDesc": "I’m Mingzhe. I build AI applications — and explore the systems that make them work.",
  "heroCta": "Explore my work",
  "resume": "Download CV",
  "scroll": "SCROLL TO EXPLORE",
  "storyTag": "A PORTFOLIO IN FIVE DIMENSIONS",
  "index": "INDEX",
  "optical": "ORIGINAL WEBGL STUDY",
  "live": "REAL-TIME RENDER",
  "static": "STATIC VIEW",
  "software": "SOFTWARE 3D",
  "motionOn": "Pause motion",
  "motionOff": "Enable motion",
  "fairyKicker": "01 / A DESKTOP PRESENCE",
  "fairyA": "Meet",
  "fairyB": "Fairy.",
  "fairyDesc": "Building an intelligent assistant for personal devices, bringing conversations, document retrieval and controlled tool use into everyday work.",
  "fairyNote": "Local-first · Windows · In development",
  "case": "Inside the project",
  "source": "View source",
  "fairyVisual": "INTERACTIVE VISUAL STUDY · NOT AN APP CAPTURE",
  "idle": "Idle",
  "think": "Think",
  "voice": "Voice",
  "coreKicker": "02 / BENEATH THE INTERFACE",
  "coreA": "The systems",
  "coreB": "behind the spark.",
  "coreDesc": "A shared foundation for the personal and enterprise workbenches: model and tool capabilities, recorded tasks, and state after refresh, cancellation or retry.",
  "coreBoundary": "SHARED BY MOJOCLAW + MOJOAX · FAIRY HAS ITS OWN CORE",
  "coreTag1": "Contracts",
  "coreTag2": "Execution",
  "coreTag3": "Recovery",
  "mojoKicker": "03 / ONE CORE. TWO CONTEXTS.",
  "mojoA": "Personal focus.",
  "mojoB": "Enterprise intent.",
  "mojoDesc": "MojoClaw brings personal AI SaaS to web and desktop, while MojoAX organises work for enterprise teams. Both draw on MojoCore, with distinct experiences for their users.",
  "clawLabel": "Personal AI SaaS · Web & desktop",
  "axLabel": "For teams & organisations",
  "diagram": "ARCHITECTURE ILLUSTRATION · NOT A LIVE SESSION",
  "methodKicker": "04 / HOW I BUILD",
  "methodA": "AI-assisted.",
  "methodB": "Human-directed.",
  "methodDesc": "The tools accelerate implementation. The work is deciding what to build, giving it context, and checking what actually happened.",
  "methodCallout": "A passing test is evidence.\nNot the whole product.",
  "methodProof": "Examples of my development approach, not a recording of a tool session.",
  "step1": "Define the problem",
  "step1d": "Turn an idea into requirements, boundaries and acceptance criteria.",
  "step2": "Build with context",
  "step2d": "Use Codex and Claude with repository context, constraints and focused tasks.",
  "step3": "Inspect the result",
  "step3d": "Review changes, run focused checks and reproduce real application behaviour.",
  "step4": "Iterate deliberately",
  "step4d": "Investigate failures, refine the task and verify the next change.",
  "archiveKicker": "SELECTED WORK & EARLIER EXPLORATIONS",
  "archiveA": "Built from",
  "archiveB": "curiosity.",
  "archiveDesc": "Four ongoing AI projects. Five earlier experiments. A record of learning by making.",
  "all": "All projects",
  "ai": "AI systems",
  "archive": "Earlier work",
  "detail": "Read project",
  "record": "Project record",
  "publicSource": "Public repository",
  "private": "Private project",
  "aboutKicker": "THE PERSON BEHIND THE PROJECTS",
  "aboutA": "Business systems.",
  "aboutB": "Builder’s mindset.",
  "aboutDesc": "I’m Mingzhe Zhang — also known as Richie — an RMIT Business Information Systems graduate based in Melbourne. My recent work centres on AI-assisted application development, agent workflows and desktop interfaces.",
  "aboutDesc2": "I use Codex and Claude throughout planning, implementation, debugging and validation. My focus is turning an idea into working behaviour, while being clear about what is still in development.",
  "background": "Background",
  "degree": "Bachelor of Business Information Systems",
  "diploma": "Diploma of Information Technology",
  "intern": "Intern · Beijing Anxin",
  "internDesc": "Supported big-data platform construction and maintenance; contributed to frontend and backend tasks under supervision, with exposure to production-safety AI and system monitoring.",
  "school": "Haileybury · Secondary education",
  "languages": "English / Mandarin (native)",
  "citizen": "Australian citizen",
  "guitar": "Away from the screen: guitar.",
  "skillsTitle": "Tools I work with",
  "skillsNote": "Project technologies and learning foundations — not proficiency scores.",
  "skills1": "AI-assisted development",
  "skills2": "Application technologies",
  "skills3": "Systems & tooling",
  "skills4": "Applied AI",
  "contactKicker": "HAVE A PROJECT, A QUESTION, OR AN IDEA?",
  "contactA": "Let’s build",
  "contactB": "something real.",
  "contactDesc": "Open to conversations about AI applications, agent systems and opportunities to learn through real projects.",
  "copy": "Copy email",
  "copied": "Email copied",
  "footer": "Designed around the work. Built for the curious.",
  "evidence": "Content & source notes",
  "close": "Close",
  "contribution": "My contribution",
  "capabilities": "Project scope",
  "challenge": "What I focus on",
  "basis": "Source basis",
  "limits": "Current limits",
  "sourceAction": "Open source record",
  "catalogCount": "PROJECTS",
  "evidenceTitle": "The work, with context.",
  "evidenceIntro": "This site separates project descriptions, personal contribution statements and runtime verification. It does not turn every repository claim into a release claim.",
  "evidenceCv": "Identity, education, internship and personal contribution statements come from the supplied original and updated CVs.",
  "evidenceRepo": "Public Fairy documentation and earlier portfolio configuration provide project context. Reviewed private Mojo documentation supports only public-safe summaries; private source is not distributed.",
  "evidenceScope": "In a 2026-09-19 verification round, local projects were run or previewed to capture real evidence: the Fairy desktop UI, the Dreambound Canvas/WebGL2 build (also hosted here as a playable demo), the Tarot and Goodnight UIs, the Web Change CLI and renderer, and the released Mi Format Converter executable. Private MojoCore/MojoClaw/MojoAX source stays closed, and server-backed projects are not presented as hosted services. Illustrations are labelled.",
  "evidencePrivacy": "The downloadable CV contains supplied contact information. The website omits the residential street address and does not contain API keys, private repository paths or analytics trackers.",
  "menu": "Open navigation",
  "contactLink": "Email Mingzhe",
  "experienceSource": "Background from supplied CVs",
  "modeNative": "NATIVE SCROLL",
  "modeGsap": "GSAP SCROLL",
  "fallback": "The 3D view is unavailable. All project content remains accessible.",
  "look": "VIEW STUDY",
  "back": "Back to top"
 },
 "zh": {
  "navWork": "作品",
  "navMethod": "开发方法",
  "navAbout": "关于我",
  "navContact": "联系我",
  "skip": "跳到项目列表",
  "role": "AI 应用开发者",
  "location": "澳大利亚 · 墨尔本",
  "heroKicker": "独立开发 · AI 与软件",
  "heroA": "让想法，",
  "heroB": "成为智能。",
  "heroDesc": "我是 Mingzhe。开发 AI 应用，也探索让它们真正运转的底层系统。",
  "heroCta": "探索我的作品",
  "resume": "下载简历",
  "scroll": "向下滚动，进入我的开发世界",
  "storyTag": "穿越五个维度的个人作品集",
  "index": "目录",
  "optical": "原创 WEBGL 视觉探索",
  "live": "实时渲染",
  "static": "静态视图",
  "software": "软件 3D",
  "motionOn": "暂停动态效果",
  "motionOff": "开启动效",
  "fairyKicker": "01 / 不止一个聊天窗口",
  "fairyA": "认识",
  "fairyB": "Fairy。",
  "fairyDesc": "以成为个人终端的智能助手为目标，将对话、资料检索与受控工具操作融入日常工作。",
  "fairyNote": "本地优先 · Windows · 持续开发",
  "case": "深入了解项目",
  "source": "查看源码",
  "fairyVisual": "交互视觉演绎 · 非原生应用截图",
  "idle": "待机",
  "think": "思考",
  "voice": "语音",
  "coreKicker": "02 / 界面之下",
  "coreA": "智能背后，",
  "coreB": "是系统。",
  "coreDesc": "个人版与企业版共用的运行基础：组织模型和工具、记录任务，并关注刷新、取消和重试之后，界面应该恢复什么状态。",
  "coreBoundary": "由 MOJOCLAW 与 MOJOAX 共享 · FAIRY 拥有自己的 CORE",
  "coreTag1": "契约",
  "coreTag2": "执行",
  "coreTag3": "恢复",
  "mojoKicker": "03 / 同一核心，不同场景",
  "mojoA": "个人的专注。",
  "mojoB": "企业的协同。",
  "mojoDesc": "MojoClaw 面向个人，提供网页与桌面 AI SaaS 工作台；MojoAX 面向企业组织团队工作。两种产品共享 MojoCore 的能力基础，但保留不同的使用体验。",
  "clawLabel": "个人 AI SaaS · 网页与桌面",
  "axLabel": "面向团队与组织",
  "diagram": "架构示意 · 非真实运行会话",
  "methodKicker": "04 / 我的开发方式",
  "methodA": "AI 辅助。",
  "methodB": "由我判断。",
  "methodDesc": "工具加快实现。真正的工作，是决定要做什么、提供足够的上下文，并核实实际发生了什么。",
  "methodCallout": "测试通过是一份证据。\n不是产品的全部。",
  "methodProof": "这里展示开发方法，不是 AI 工具会话的录屏。",
  "step1": "明确问题",
  "step1d": "把想法拆解为需求、模块边界与验收标准。",
  "step2": "带着上下文开发",
  "step2d": "结合仓库上下文、约束与具体任务使用 Codex 和 Claude。",
  "step3": "检查实际结果",
  "step3d": "审查修改、运行针对性检查，并复现真实应用行为。",
  "step4": "有依据地迭代",
  "step4d": "排查失败原因、调整任务，再验证下一次修改。",
  "archiveKicker": "重点项目与早期探索",
  "archiveA": "从好奇，",
  "archiveB": "到作品。",
  "archiveDesc": "四个持续开发的 AI 项目，五个早期探索。记录在实践中学习的过程。",
  "all": "全部项目",
  "ai": "AI 系统",
  "archive": "早期作品",
  "detail": "了解项目",
  "record": "项目记录",
  "publicSource": "公开仓库",
  "private": "私有项目",
  "aboutKicker": "作品背后的人",
  "aboutA": "信息系统背景。",
  "aboutB": "持续构建的习惯。",
  "aboutDesc": "我是 Mingzhe Zhang，也可以叫我 Richie，毕业于 RMIT Business Information Systems，现居墨尔本。近期主要探索 AI 辅助应用开发、智能体工作流和桌面交互。",
  "aboutDesc2": "从规划、实现到排错与验证，我会持续使用 Codex 和 Claude。重点是把想法变成真实可用的行为，同时清楚区分哪些部分仍在开发。",
  "background": "学习与经历",
  "degree": "商业信息系统学士",
  "diploma": "信息技术文凭",
  "intern": "实习 · Beijing Anxin",
  "internDesc": "协助大数据平台建设与维护，在指导下参与前后端任务，接触安全生产 AI 应用与系统监测。",
  "school": "Haileybury · 中学教育",
  "languages": "英语 / 中文（母语）",
  "citizen": "澳大利亚公民",
  "guitar": "屏幕之外：弹吉他。",
  "skillsTitle": "开发中使用的工具",
  "skillsNote": "项目技术与学习基础，而不是技能熟练度评分。",
  "skills1": "AI 辅助开发",
  "skills2": "应用技术",
  "skills3": "系统与工具",
  "skills4": "AI 应用能力",
  "contactKicker": "有项目、有问题，或者有一个新想法？",
  "contactA": "一起做点",
  "contactB": "真正的东西。",
  "contactDesc": "欢迎交流 AI 应用、智能体系统，以及在真实项目中持续学习的机会。",
  "copy": "复制邮箱",
  "copied": "邮箱已复制",
  "footer": "以真实作品为中心，为好奇而构建。",
  "evidence": "内容与来源说明",
  "close": "关闭",
  "contribution": "我的参与",
  "capabilities": "项目范围",
  "challenge": "关注的问题",
  "basis": "来源依据",
  "limits": "当前限制",
  "sourceAction": "查看原始记录",
  "catalogCount": "个项目",
  "evidenceTitle": "展示作品，也保留上下文。",
  "evidenceIntro": "本站区分项目描述、个人贡献陈述和实际运行验证，不把仓库中的每一句描述都转换为正式发布承诺。",
  "evidenceCv": "身份、教育、实习与个人贡献表述，依据已提供的原简历和更新版简历。",
  "evidenceRepo": "Fairy 公开文档和旧作品集配置提供项目背景；已查阅的私有 Mojo 文档只用于适合公开的概括，不分发私有源码。",
  "evidenceScope": "2026-09-19 的验证轮次中，本地项目经运行或预览以采集真实证据：Fairy 桌面界面、Dreambound Canvas/WebGL2 构建（并在本站托管为可玩演示）、Tarot 与 Goodnight 界面、Web Change 的 CLI 与渲染层，以及已发布的 Mi 格式转换 exe。私有 MojoCore/MojoClaw/MojoAX 源码继续不公开，需要服务端的项目不冒充托管服务，示意图均有标识。",
  "evidencePrivacy": "下载简历包含已提供的联系方式。网页不展示住宅街道地址，不包含 API 密钥、私有仓库路径或分析追踪器。",
  "menu": "打开导航",
  "contactLink": "给 Mingzhe 发邮件",
  "experienceSource": "背景信息来自已提供的简历",
  "modeNative": "原生滚动",
  "modeGsap": "GSAP 滚动",
  "fallback": "3D 视图暂不可用，所有项目信息仍可正常阅读。",
  "look": "视觉探索",
  "back": "返回顶部"
 }
};
